# Generated by Django 5.0.6 on 2025-11-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='staff_identifier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='staff_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='staff_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
