# Generated by Django 5.0.6 on 2025-11-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
